menu:
    Blog: /
    Archive: /archives/
    Me: /me/
    GitHub: https://github.com/milkdeliver
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
google-analytics:
ga: UA-134861474-2

# Copyright Infomation
startyear: 2015
